### ISSUE TITLE
models removed?

### ISSUE THREAD

**Issue by artnose** [gafr/chainer-fast-neuralstyle-models#13]
Hi, 
  Just wondering what happened to some of the models, there used to be more. 
Hoping we can get more models in here.

**Comment by gafr** [comment]
we didnt remove any models. You can skip through the commit log, but I could not find any removals

**Comment by artnose** [comment]
https://github.com/gafr/chainer-fast-neuralstyle-models/commit/7a58f23f4938ed1b736ea2f37f65efdd8eb7b067   
here's one removed

**Comment by gafr** [comment]
hmm you are right, maybe @6o6o has more info.

**Comment by 6o6o** [comment]
I got involved with an app development and decided to contribute those models. This means they are company's intellectual property so they had to be removed. Sorry for inconvenience.
