### ISSUE TITLE
Model Sizes

### ISSUE THREAD

**Issue by DylanAlloy** [gafr/chainer-fast-neuralstyle-models#2]
First off,  you guys are champions. I can't wait to contribute.

Secondly did you notice that your model filesizes are way smaller? Why do you think that is?

**Comment by 6o6o** [comment]
Thanks. What do you mean smaller? They're all exactly the same 6.5 MiB. What are you comparing with?

**Comment by austingg** [comment]
@6o6o  I think @DylanAlloy is comparing with vgg like description model. In fact, after training, the style transfer only need generation part of the whole network, which only has some conv layers.

**Comment by 6o6o** [comment]
Yeah, @DylanAlloy, the algorithm uses two networks. The feature extraction is done by VGG. That network is huge. It would be impractical to train it on conventional PCs. You have to train the generator network.

**Comment by DylanAlloy** [comment]
Oooh okay so I may have been training it on a larger network.

https://github.com/DylanAlloy/NeuralStyle-WebApp/tree/master/chainer-fast-neuralstyle-master/models

You can see that yours are vastly smaller (I haven't tried using yours yet, though I have them ready for my webapp to attempt.)
