### ISSUE TITLE
Correct params to train.py because I have a rare error like noise

### ISSUE THREAD

**Issue by nandexsp** [gafr/chainer-fast-neuralstyle-models#3]
Why the images with the model has noise?
I used "python train.py -s style1.jpg -d train2014 -g 0 "

what is the correct params?

**Comment by 6o6o** [comment]
It happens. Depending on your style image and dataset the noise may be more or less pronounced. There's no straightforward solution. I'd suggest making checkpoints every 20k images as you train with `-c 20000` and then choosing the model which looks best.

**Comment by nandexsp** [comment]
I'm using the full coco dataset (82XXX) . Your solution is uses: 
python train.py -s style1.jpg -d train2014 -g 0 -c 20000 -size 512

and then choos the best model? ok, I will try and report the results
